// Code generated by MockGen. DO NOT EDIT.
// Source: wallet_zero_balance_gate.go
//
// Generated by this command:
//
//	mockgen -source=wallet_zero_balance_gate.go -destination=mocks/wallet_zero_balance_gate_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletZeroBalanceChecker is a mock of WalletZeroBalanceChecker interface.
type MockWalletZeroBalanceChecker struct {
	ctrl     *gomock.Controller
	recorder *MockWalletZeroBalanceCheckerMockRecorder
	isgomock struct{}
}

// MockWalletZeroBalanceCheckerMockRecorder is the mock recorder for MockWalletZeroBalanceChecker.
type MockWalletZeroBalanceCheckerMockRecorder struct {
	mock *MockWalletZeroBalanceChecker
}

// NewMockWalletZeroBalanceChecker creates a new mock instance.
func NewMockWalletZeroBalanceChecker(ctrl *gomock.Controller) *MockWalletZeroBalanceChecker {
	mock := &MockWalletZeroBalanceChecker{ctrl: ctrl}
	mock.recorder = &MockWalletZeroBalanceCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletZeroBalanceChecker) EXPECT() *MockWalletZeroBalanceCheckerMockRecorder {
	return m.recorder
}

// AssertZeroBalance mocks base method.
func (m *MockWalletZeroBalanceChecker) AssertZeroBalance(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssertZeroBalance", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssertZeroBalance indicates an expected call of AssertZeroBalance.
func (mr *MockWalletZeroBalanceCheckerMockRecorder) AssertZeroBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertZeroBalance", reflect.TypeOf((*MockWalletZeroBalanceChecker)(nil).AssertZeroBalance), ctx, userID)
}
