// Code generated by MockGen. DO NOT EDIT.
// Source: user_active_gate.go
//
// Generated by this command:
//
//	mockgen -source=user_active_gate.go -destination=mocks/user_active_gate_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserActiveGate is a mock of UserActiveGate interface.
type MockUserActiveGate struct {
	ctrl     *gomock.Controller
	recorder *MockUserActiveGateMockRecorder
	isgomock struct{}
}

// MockUserActiveGateMockRecorder is the mock recorder for MockUserActiveGate.
type MockUserActiveGateMockRecorder struct {
	mock *MockUserActiveGate
}

// NewMockUserActiveGate creates a new mock instance.
func NewMockUserActiveGate(ctrl *gomock.Controller) *MockUserActiveGate {
	mock := &MockUserActiveGate{ctrl: ctrl}
	mock.recorder = &MockUserActiveGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserActiveGate) EXPECT() *MockUserActiveGateMockRecorder {
	return m.recorder
}

// EnsureActive mocks base method.
func (m *MockUserActiveGate) EnsureActive(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureActive", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureActive indicates an expected call of EnsureActive.
func (mr *MockUserActiveGateMockRecorder) EnsureActive(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureActive", reflect.TypeOf((*MockUserActiveGate)(nil).EnsureActive), ctx, userID)
}
